#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde::{Deserialize, Serialize};
use std::{ffi::OsStr, fs, io::{BufRead, BufReader, Write}, path::PathBuf, process::{Command, Stdio}, sync::{Arc, Mutex}};
#[cfg(windows)]
use std::os::windows::process::CommandExt;
use tauri::{AppHandle, Emitter, Manager};

const YTDLP_URL: &str = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe";
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Track { id: String, title: String, artist: String, duration: String, source_url: String, artwork: Option<String> }
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct DownloadRequest { source_url: String, title: String }

fn ytdlp_path(app: &AppHandle) -> Result<PathBuf, String> { let dir = app.path().app_local_data_dir().map_err(|e| e.to_string())?.join("tools"); fs::create_dir_all(&dir).map_err(|e| format!("Couldn't create the tools folder: {e}"))?; Ok(dir.join("yt-dlp.exe")) }
fn hidden_command(program: impl AsRef<OsStr>) -> Command { let mut command = Command::new(program); #[cfg(windows)] { command.creation_flags(0x08000000); } command }
fn progress_percent(line: &str) -> Option<f64> { line.split_whitespace().find(|part| part.ends_with('%'))?.trim_end_matches('%').parse::<f64>().ok().map(|value| value.clamp(0.0, 100.0)) }
fn validate_public_youtube(url: &str) -> Result<(), String> { let permitted = ["https://www.youtube.com/", "https://youtube.com/", "https://youtu.be/"]; if permitted.iter().any(|prefix| url.starts_with(prefix)) { Ok(()) } else { Err("Only public YouTube links are supported.".into()) } }

#[tauri::command]
fn install_ytdlp(app: AppHandle) -> Result<String, String> { let target = ytdlp_path(&app)?; let temp = target.with_extension("download"); let status = hidden_command("curl.exe").args(["--fail", "--location", "--silent", "--show-error", "--output", temp.to_string_lossy().as_ref(), YTDLP_URL]).status().map_err(|_| "Couldn't start Windows curl to fetch yt-dlp.".to_string())?; if !status.success() { return Err("Couldn't download yt-dlp. Check your connection and try again.".into()); } fs::rename(&temp, &target).map_err(|e| format!("Couldn't activate yt-dlp: {e}"))?; Ok("yt-dlp is ready".into()) }
#[tauri::command]
fn runtime_status(app: AppHandle) -> serde_json::Value { let ytdlp = ytdlp_path(&app).ok().is_some_and(|path| path.exists()); serde_json::json!({ "desktop": true, "downloader": if ytdlp { "ready" } else { "not-installed" } }) }
fn search_youtube_sync(app: AppHandle, query: String) -> Result<Vec<Track>, String> { let bin = ytdlp_path(&app)?; if !bin.exists() { return Err("Install the free yt-dlp provider in Settings to search YouTube.".into()); } let query = query.trim(); if query.is_empty() { return Ok(vec![]); } let output = hidden_command(&bin).args(["--dump-single-json", "--no-flat-playlist", &format!("ytsearch10:{query}")]).output().map_err(|_| "nont couldn't start yt-dlp. Reinstall it from Settings.".to_string())?; if !output.status.success() { return Err("YouTube search didn't complete. Try again shortly.".into()); } let data: serde_json::Value = serde_json::from_slice(&output.stdout).map_err(|_| "Search returned an unreadable result.".to_string())?; Ok(data["entries"].as_array().unwrap_or(&vec![]).iter().filter_map(|entry| { let id = entry["id"].as_str()?.to_string(); let artwork = entry["thumbnails"].as_array().and_then(|images| images.iter().rev().find_map(|image| image["url"].as_str())).or(entry["thumbnail"].as_str()).map(str::to_owned); Some(Track { source_url: format!("https://www.youtube.com/watch?v={id}"), id, title: entry["title"].as_str().unwrap_or("Untitled").to_string(), artist: entry["channel"].as_str().or(entry["uploader"].as_str()).unwrap_or("YouTube").to_string(), duration: entry["duration_string"].as_str().unwrap_or("—").to_string(), artwork }) }).collect()) }
#[tauri::command]
async fn search_youtube(app: AppHandle, query: String) -> Result<Vec<Track>, String> { tauri::async_runtime::spawn_blocking(move || search_youtube_sync(app, query)).await.map_err(|_| "Search worker stopped unexpectedly.".to_string())? }
#[tauri::command]
fn resolve_audio(app: AppHandle, source_url: String) -> Result<String, String> { validate_public_youtube(&source_url)?; let bin = ytdlp_path(&app)?; if !bin.exists() { return Err("Install the free yt-dlp provider in Settings first.".into()); } let output = hidden_command(&bin).args(["--no-playlist", "-f", "bestaudio/best", "-g", &source_url]).output().map_err(|_| "nont couldn't start yt-dlp.".to_string())?; if !output.status.success() { return Err("This public media couldn't be resolved for playback.".into()); } String::from_utf8(output.stdout).map_err(|_| "The audio URL was unreadable.".to_string()).map(|value| value.trim().to_string()) }
#[tauri::command]
fn queue_download(app: AppHandle, request: DownloadRequest) -> Result<(), String> { validate_public_youtube(&request.source_url)?; let bin = ytdlp_path(&app)?; if !bin.exists() { return Err("Install the free yt-dlp provider in Settings first.".into()); } let folder = app.path().download_dir().map_err(|e| e.to_string())?.join("nont"); fs::create_dir_all(&folder).map_err(|e| e.to_string())?; let log = folder.join("nont-download.log"); let template = folder.join("%(artist)s - %(title)s.%(ext)s").to_string_lossy().to_string(); let source_url = request.source_url; let track_title = request.title; std::thread::spawn(move || { let result = (|| -> Result<(), String> { let log_file = Arc::new(Mutex::new(fs::File::create(&log).map_err(|e| format!("Couldn't create download log: {e}"))?)); let mut child = hidden_command(&bin).args(["--no-playlist", "--continue", "--newline", "-f", "bestaudio[ext=m4a]/bestaudio/best", "-o", &template, &source_url]).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn().map_err(|_| "Couldn't start the download.".to_string())?; let stderr = child.stderr.take().ok_or("Couldn't read download errors.")?; let stderr_log = Arc::clone(&log_file); let stderr_app = app.clone(); let stderr_url = source_url.clone(); let stderr_thread = std::thread::spawn(move || { for line in BufReader::new(stderr).lines().map_while(Result::ok) { let _ = writeln!(stderr_log.lock().unwrap(), "{line}"); if let Some(percent) = progress_percent(&line) { let _ = stderr_app.emit("download.progress", serde_json::json!({"sourceUrl": &stderr_url, "percent": percent})); } } }); let stdout = child.stdout.take().ok_or("Couldn't read download progress.")?; for line in BufReader::new(stdout).lines().map_while(Result::ok) { let _ = writeln!(log_file.lock().unwrap(), "{line}"); if let Some(percent) = progress_percent(&line) { let _ = app.emit("download.progress", serde_json::json!({"sourceUrl": &source_url, "percent": percent})); } } let status = child.wait().map_err(|_| "Couldn't wait for the download.".to_string())?; let _ = stderr_thread.join(); if status.success() { Ok(()) } else { Err("Download failed. See Downloads/nont/nont-download.log for details.".into()) } })(); let state = if result.is_ok() { "completed" } else { "failed" }; let _ = app.emit("download.finished", serde_json::json!({"sourceUrl": source_url, "title": track_title, "state": state, "error": result.err()})); }); Ok(()) }
#[tauri::command]
fn clear_completed_downloads(app: AppHandle) -> Result<u32, String> { let folder = app.path().download_dir().map_err(|e| e.to_string())?.join("nont"); if !folder.exists() { return Ok(0); } let mut deleted = 0; for item in fs::read_dir(&folder).map_err(|e| format!("Couldn't read downloads: {e}"))? { let path = item.map_err(|e| e.to_string())?.path(); if path.file_name().is_some_and(|name| name == "nont-download.log") || path.is_dir() { continue; } fs::remove_file(&path).map_err(|e| format!("Couldn't remove {}: {e}", path.display()))?; deleted += 1; } Ok(deleted) }
fn main() { tauri::Builder::default().setup(|app| { if let Some(window) = app.get_webview_window("main") { let _ = window.center(); } Ok(()) }).invoke_handler(tauri::generate_handler![install_ytdlp, runtime_status, search_youtube, resolve_audio, queue_download, clear_completed_downloads]).run(tauri::generate_context!()).expect("error while running nont"); }
