import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { listen } from '@tauri-apps/api/event'
import './App.css'
import './theme.css'

type Track = { id: string; title: string; artist: string; duration: string; sourceUrl?: string; artwork?: string }
type Download = Track & { state: 'queued' | 'downloading' | 'completed' | 'failed'; progress: number }
type Page = 'Home' | 'Search' | 'Your Library' | 'Playlists' | 'Downloads' | 'Liked Songs' | 'Recently Played' | 'Settings'
const starter: Track[] = []
const stateKey = 'nont:v1:'
function read<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(stateKey + key) || '') as T } catch { return fallback } }

function App() {
  const [page, setPage] = useState<Page>('Home'); const [query, setQuery] = useState('')
  const [queue, setQueue] = useState<Track[]>(() => read('queue', [])); const [likes, setLikes] = useState<string[]>(() => read('likes', []))
  const [downloads, setDownloads] = useState<Download[]>(() => read('downloads', [])); const [history, setHistory] = useState<Track[]>(() => read('history', []))
  const [current, setCurrent] = useState<Track | null>(() => read('current', null)); const [playing, setPlaying] = useState(false); const [toast, setToast] = useState('')
  const [newPlaylist, setNewPlaylist] = useState(''); const [playlists, setPlaylists] = useState<{name: string, tracks: Track[]}[]>(() => read('playlists', [])); const [openPlaylist, setOpenPlaylist] = useState<string | null>(null); const [playlistPicker, setPlaylistPicker] = useState<Track | null>(null); const [results, setResults] = useState<Track[]>(starter); const [providerReady, setProviderReady] = useState(false); const [elapsed, setElapsed] = useState(0); const [mediaDuration, setMediaDuration] = useState(0); const [expanded, setExpanded] = useState(false); const audio = useRef<HTMLAudioElement | null>(null)
  const native = Boolean((window as Window & { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__)
  useEffect(() => { localStorage.setItem(stateKey + 'queue', JSON.stringify(queue)) }, [queue]); useEffect(() => { localStorage.setItem(stateKey + 'likes', JSON.stringify(likes)) }, [likes]); useEffect(() => { localStorage.setItem(stateKey + 'downloads', JSON.stringify(downloads)) }, [downloads]); useEffect(() => { localStorage.setItem(stateKey + 'history', JSON.stringify(history)) }, [history]); useEffect(() => { localStorage.setItem(stateKey + 'current', JSON.stringify(current)) }, [current]); useEffect(() => { localStorage.setItem(stateKey + 'playlists', JSON.stringify(playlists)) }, [playlists]); useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 2600); return () => clearTimeout(id) }, [toast])
  useEffect(() => { if (native) invoke<{ downloader: string }>('runtime_status').then(s => setProviderReady(s.downloader === 'ready')).catch(() => setProviderReady(false)) }, [native])
  useEffect(() => { if (!native) return; let unlisten: (() => void) | undefined; listen<{sourceUrl:string,state:Download['state'],error?:string}>('download.finished', event => { setDownloads(items => items.map(item => item.sourceUrl === event.payload.sourceUrl ? {...item, state:event.payload.state, progress:event.payload.state === 'completed' ? 100 : item.progress} : item)); tell(event.payload.state === 'completed' ? 'Download completed' : event.payload.error || 'Download failed') }).then(fn => { unlisten = fn }); return () => unlisten?.() }, [native])
  useEffect(() => { if (!native) return; let unlisten: (() => void) | undefined; listen<{sourceUrl:string,percent:number}>('download.progress', event => { setDownloads(items => items.map(item => item.sourceUrl === event.payload.sourceUrl ? {...item, state:'downloading', progress:event.payload.percent} : item)) }).then(fn => { unlisten = fn }); return () => unlisten?.() }, [native])
  const tell = (message: string) => setToast(message); const play = async (t: Track) => { setCurrent(t); setPlaying(true); setElapsed(0); setMediaDuration(0); setHistory(v => [t, ...v.filter(x => x.id !== t.id)].slice(0, 50)); if (native && t.sourceUrl) { try { const url = await invoke<string>('resolve_audio', { sourceUrl: t.sourceUrl }); audio.current?.pause(); const player = new Audio(url); audio.current = player; player.ontimeupdate = () => setElapsed(player.currentTime); player.onloadedmetadata = () => setMediaDuration(Number.isFinite(player.duration) ? player.duration : 0); player.onplay = () => setPlaying(true); player.onpause = () => setPlaying(false); player.onended = () => { setPlaying(false); setElapsed(0) }; await player.play() } catch (e) { setPlaying(false); tell(String(e)) } } else tell(`Playing ${t.title}`) }
  const openWebSearch = (term: string) => { window.open(`https://www.youtube.com/results?search_query=${encodeURIComponent(term)}`, '_blank', 'noopener,noreferrer'); tell('Opening YouTube results in a new tab') }
  const searchYouTube = async () => { if (!query.trim()) return; if (!native) { openWebSearch(query); return } try { const found = await invoke<Track[]>('search_youtube', { query }); setResults(found); setPage('Search') } catch (e) { tell(String(e)); setPage('Settings') } }
  const installProvider = async () => { try { tell('Installing yt-dlp…'); await invoke('install_ytdlp'); setProviderReady(true); tell('YouTube search is ready') } catch (e) { tell(String(e)) } }
  const like = (t: Track) => setLikes(v => v.includes(t.id) ? v.filter(id => id !== t.id) : [...v, t.id]); const addQueue = (t: Track) => { setQueue(v => [...v, t]); tell('Added to queue') }; const addToPlaylist = (name: string, track: Track) => { setPlaylists(v => v.map(p => p.name === name ? {...p, tracks: p.tracks.some(t => t.id === track.id) ? p.tracks : [...p.tracks, track]} : p)); setPlaylistPicker(null); tell(`Added to ${name}`) }; const download = async (t: Track) => { if (!native) return tell('Downloads are available in the nont desktop app.'); if (!t.sourceUrl) return tell('Search YouTube for a downloadable track.'); if (downloads.some(x => x.id === t.id)) return tell('Already in downloads'); try { await invoke('queue_download', { request: { sourceUrl: t.sourceUrl, title: t.title } }); setDownloads(v => [...v, {...t, state: 'downloading', progress: 0}]); tell('Download started — saved in Downloads/nont') } catch (e) { tell(String(e)) } }
  const tracks = (items: Track[]) => items.length ? <><div className="tracks">{items.map((t, i) => <div className="track" key={`${t.id}-${i}`}><small>{i + 1}</small><div className="cover">{t.artwork ? <img src={t.artwork} alt="" /> : '♪'}</div><div><b>{t.title}</b><span>{t.artist}</span></div><small>{t.duration}</small><button className={likes.includes(t.id) ? 'liked' : ''} onClick={() => like(t)}>♥</button><button onClick={() => addQueue(t)}>＋</button><button className="playlist-add" onClick={() => playlists.length ? setPlaylistPicker(t) : tell('Create a playlist first, then use this button.')}>＋ Playlist</button><button onClick={() => download(t)}>↓</button><button className="play" onClick={() => play(t)}>▶</button></div>)}</div>{playlistPicker && <div className="playlist-picker"><b>Add “{playlistPicker.title}” to:</b>{playlists.map(p => <button key={p.name} onClick={() => addToPlaylist(p.name, playlistPicker)}>{p.name}</button>)}<button className="cancel" onClick={() => setPlaylistPicker(null)}>Cancel</button></div>}</> : <div className="empty">Nothing here yet.</div>
  const body = () => {
    if (page === 'Search') return <><Title label="Search" title="Find what you want to play" copy={providerReady ? "YouTube search is connected through your local yt-dlp provider." : "Install the free local provider in Settings, then search public YouTube videos."}/><h2>Results</h2>{tracks(results)}</>
    if (page === 'Downloads') { const completed = downloads.some(x => x.state === 'completed'); return <><Title label="Downloads" title="Download manager" copy="Jobs persist and are handed to the native download scheduler."/>{completed && <button className="clear-downloads" onClick={async () => { if (!confirm('Remove all completed downloads from your Downloads/nont folder?')) return; try { const count = await invoke<number>('clear_completed_downloads'); setDownloads(items => items.filter(x => x.state !== 'completed')); tell(`${count} downloaded file${count === 1 ? '' : 's'} removed`) } catch (e) { tell(String(e)) } }}>Clear completed downloads</button>}{downloads.length ? <div className="tracks">{downloads.map(x => <div className="download" key={x.id}><div className="cover">↓</div><div><b>{x.title}</b><span>{x.artist} · {x.state}</span><i><em style={{width: `${x.progress}%`}} /></i></div><small>{x.progress}%</small></div>)}</div> : <div className="empty"><b>Nothing downloaded yet.</b><br/>Search for something you love and download it with one click.</div>}</> }
    if (page === 'Liked Songs') return <><Title label="Collection" title="Liked Songs"/>{tracks([...starter, ...queue].filter((x, i, all) => likes.includes(x.id) && all.findIndex(y => y.id === x.id) === i))}</>
    if (page === 'Recently Played') return <><Title label="History" title="Recently Played"/>{tracks(history)}</>
    if (page === 'Your Library') return <><Title label="Local music" title="Your Library" copy="Downloaded and imported tracks appear here, playable offline."/>{tracks(downloads.filter(x => x.state === 'completed'))}</>
    if (page === 'Playlists') { const playlist = playlists.find(x => x.name === openPlaylist); return playlist ? <><button className="back" onClick={() => setOpenPlaylist(null)}>← All playlists</button><PlaylistCover playlist={playlist}/><Title label="Playlist" title={playlist.name} copy={`${playlist.tracks.length} tracks`}/><div className="playlist-actions"><button onClick={() => playlist.tracks[0] && play(playlist.tracks[0])}>Play</button><button onClick={() => {setPage('Search');tell('Search for a track, then use + Playlist.')}}>Add tracks</button></div>{tracks(playlist.tracks)}</> : <><Title label="Collection" title="Your Playlists"/><div className="create"><input value={newPlaylist} onChange={e => setNewPlaylist(e.target.value)} onKeyDown={e => { if(e.key === 'Enter' && newPlaylist.trim()){ setPlaylists(v => [...v, {name:newPlaylist.trim(),tracks:[]}]); setNewPlaylist('') } }} placeholder="New playlist name"/><button onClick={() => { if(newPlaylist.trim()){setPlaylists(v => [...v,{name:newPlaylist.trim(),tracks:[]}]);setNewPlaylist('');tell('Playlist created')}}}>Create playlist</button></div>{playlists.length ? <div className="cards">{playlists.map(x => <article key={x.name} onClick={() => setOpenPlaylist(x.name)} role="button" tabIndex={0} onKeyDown={e => e.key === 'Enter' && setOpenPlaylist(x.name)}><PlaylistCover playlist={x}/><b>{x.name}</b><span>{x.tracks.length} tracks</span></article>)}</div> : <div className="empty">Create your first playlist.</div>}</> }
    if (page === 'Settings') return <><Title label="System" title="Settings & diagnostics" copy="nont keeps media, metadata and playback local."/><div className="settings"><p><span>Desktop runtime</span><b>{native ? 'Connected' : 'Web preview — native runtime required'}</b></p><p><span>YouTube provider</span><b>{providerReady ? 'yt-dlp ready' : 'Not installed'}</b></p><button className="provider" disabled={!native || providerReady} onClick={installProvider}>{providerReady ? 'YouTube provider installed' : 'Install free YouTube provider'}</button><p><span>Downloads</span><b>Public media is saved in Downloads/nont</b></p></div></>
    const suggestions = ['Chill music mix', 'Focus music', 'New music this week', 'Late night drive playlist']; return <><section className="hero"><small>GOOD TO HAVE YOU HERE</small><h1>Your music.<br/><em>On your terms.</em></h1><p>A local-first music home for your queue, playlists and downloads.</p><button onClick={() => setPage('Search')}>Start searching →</button></section><div className="section"><h2>Made for your next listen</h2><p className="section-copy">Explore public YouTube music searches. Suggestions become more personal as you play and like tracks.</p><div className="suggestions">{suggestions.map(s => <button key={s} onClick={() => { setQuery(s); if (native) { invoke<Track[]>('search_youtube', {query: s}).then(found => {setResults(found);setPage('Search')}).catch(e => tell(String(e))) } else {openWebSearch(s)} }}><span>♪</span><b>{s}</b><small>Search YouTube →</small></button>)}</div></div><div className="section"><h2>Continue listening</h2>{tracks(history.slice(0,4))}</div></>
  }
  const nav: Page[] = ['Home','Search','Playlists','Downloads','Liked Songs','Recently Played','Settings']
  const shownDuration = mediaDuration || 0; const time = (seconds: number) => `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, '0')}`; const progress = shownDuration ? Math.min(100, elapsed / shownDuration * 100) : 0
  const playbackControls = <><button onClick={() => { if (audio.current) { playing ? audio.current.pause() : audio.current.play() } }}>{playing ? 'Ⅱ' : '▶'}</button><i className="seek" onClick={e => { if (!audio.current || !shownDuration) return; const bounds = e.currentTarget.getBoundingClientRect(); audio.current.currentTime = ((e.clientX - bounds.left) / bounds.width) * shownDuration }}><em style={{width: `${progress}%`}}/></i><small>{time(elapsed)} / {shownDuration ? time(shownDuration) : current?.duration}</small></>
  return <main className="shell"><aside><strong className="brand">nont<span>.</span></strong><nav>{nav.map(x => <button className={page === x ? 'selected' : ''} onClick={() => {setPage(x);if(x !== 'Playlists')setOpenPlaylist(null)}} key={x}>{x === 'Home' ? '◈' : x === 'Search' ? '⌕' : x === 'Downloads' ? '↓' : x === 'Settings' ? '⚙' : '◌'} <span>{x}</span></button>)}</nav><footer><a className="support" href="https://ko-fi.com/lightnont" target="_blank" rel="noreferrer">♥ Support nont</a></footer></aside><section className="main"><header><form onSubmit={(e: FormEvent) => {e.preventDefault(); searchYouTube()}}><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="What do you want to play?"/><kbd>⌘ K</kbd></form><small className="runtime"><i/> {native ? (providerReady ? 'YouTube connected' : 'Provider setup needed') : 'Preview mode'}</small></header><article className="content">{body()}</article></section>{current && <div className="player"><button className="now" onClick={() => setExpanded(true)}><div className="cover">{current.artwork ? <img src={current.artwork} alt="" /> : '♪'}</div><p><b>{current.title}</b><span>{current.artist}</span></p></button><div className="controls">{playbackControls}</div><button className="expand" onClick={() => setExpanded(true)} aria-label="Expand player">⛶</button></div>}{expanded && current && <section className="big-player"><button className="close-player" onClick={() => setExpanded(false)}>⌄</button><div className="big-art">{current.artwork ? <img src={current.artwork} alt="" /> : '♪'}</div><p className="big-meta"><b>{current.title}</b><span>{current.artist}</span></p><div className="big-controls">{playbackControls}</div><div className="big-actions"><button onClick={() => like(current)} className={likes.includes(current.id) ? 'liked' : ''}>♥ Like</button><button onClick={() => addQueue(current)}>＋ Queue</button><button onClick={() => playlists.length ? setPlaylistPicker(current) : tell('Create a playlist first, then use this button.')}>＋ Playlist</button><button onClick={() => download(current)}>↓ Download</button></div></section>}{toast && <div className="toast">{toast}</div>}</main>
}
function Title({label,title,copy}:{label:string,title:string,copy?:string}){return <section className="title"><small>{label}</small><h1>{title}</h1>{copy && <p>{copy}</p>}</section>}
function PlaylistCover({playlist}:{playlist:{name:string,tracks:Track[]}}){const art = playlist.tracks.filter(track => track.artwork).slice(0,4); return <div className="playlist-cover" aria-label={`${playlist.name} cover`}>{art.length ? art.map(track => <img key={track.id} src={track.artwork} alt="" />) : <span>♫</span>}</div>}
export default App
