import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Track = { id: string; title: string; artist: string; duration: string }
type Download = Track & { state: 'queued' | 'downloading' | 'completed' | 'failed'; progress: number }
type Page = 'Home' | 'Search' | 'Your Library' | 'Playlists' | 'Downloads' | 'Liked Songs' | 'Recently Played' | 'Settings'
const starter: Track[] = [{ id: 'welcome', title: 'Your music, on your device', artist: 'nont', duration: '3:12' }, { id: 'local', title: 'Local-first listening', artist: 'nont', duration: '2:48' }]
const stateKey = 'nont:v1:'
function read<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(stateKey + key) || '') as T } catch { return fallback } }

function App() {
  const [page, setPage] = useState<Page>('Home'); const [query, setQuery] = useState('')
  const [queue, setQueue] = useState<Track[]>(() => read('queue', [])); const [likes, setLikes] = useState<string[]>(() => read('likes', []))
  const [downloads, setDownloads] = useState<Download[]>(() => read('downloads', [])); const [history, setHistory] = useState<Track[]>(() => read('history', []))
  const [current, setCurrent] = useState<Track | null>(() => read('current', null)); const [playing, setPlaying] = useState(false); const [toast, setToast] = useState('')
  const [newPlaylist, setNewPlaylist] = useState(''); const [playlists, setPlaylists] = useState<{name: string, tracks: Track[]}[]>(() => read('playlists', []))
  const native = Boolean((window as Window & { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__)
  useEffect(() => { localStorage.setItem(stateKey + 'queue', JSON.stringify(queue)) }, [queue]); useEffect(() => { localStorage.setItem(stateKey + 'likes', JSON.stringify(likes)) }, [likes]); useEffect(() => { localStorage.setItem(stateKey + 'downloads', JSON.stringify(downloads)) }, [downloads]); useEffect(() => { localStorage.setItem(stateKey + 'history', JSON.stringify(history)) }, [history]); useEffect(() => { localStorage.setItem(stateKey + 'current', JSON.stringify(current)) }, [current]); useEffect(() => { localStorage.setItem(stateKey + 'playlists', JSON.stringify(playlists)) }, [playlists]); useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 2600); return () => clearTimeout(id) }, [toast])
  const results = useMemo(() => query.trim() ? [{id: `q:${query}`, title: query.trim(), artist: 'Search ready', duration: '—'}] : starter, [query])
  const tell = (message: string) => setToast(message); const play = (t: Track) => { setCurrent(t); setPlaying(true); setHistory(v => [t, ...v.filter(x => x.id !== t.id)].slice(0, 50)); tell(`Playing ${t.title}`) }
  const like = (t: Track) => setLikes(v => v.includes(t.id) ? v.filter(id => id !== t.id) : [...v, t.id]); const addQueue = (t: Track) => { setQueue(v => [...v, t]); tell('Added to queue') }; const download = (t: Track) => { if (downloads.some(x => x.id === t.id)) return tell('Already in downloads'); setDownloads(v => [...v, {...t, state: 'queued', progress: 0}]); tell('Download queued') }
  const tracks = (items: Track[]) => items.length ? <div className="tracks">{items.map((t, i) => <div className="track" key={`${t.id}-${i}`}><small>{i + 1}</small><div className="cover">♪</div><div><b>{t.title}</b><span>{t.artist}</span></div><small>{t.duration}</small><button className={likes.includes(t.id) ? 'liked' : ''} onClick={() => like(t)}>♥</button><button onClick={() => addQueue(t)}>＋</button><button onClick={() => download(t)}>↓</button><button className="play" onClick={() => play(t)}>▶</button></div>)}</div> : <div className="empty">Nothing here yet.</div>
  const body = () => {
    if (page === 'Search') return <><Title label="Search" title="Find what you want to play" copy="Paste a supported YouTube URL or search when the native provider is configured."/>{query && <div className="notice">Online search is waiting for the native nont runtime: <b>{query}</b></div>}<h2>Results</h2>{tracks(results)}</>
    if (page === 'Downloads') return <><Title label="Downloads" title="Download manager" copy="Jobs persist and are handed to the native download scheduler."/>{downloads.length ? <div className="tracks">{downloads.map(x => <div className="download" key={x.id}><div className="cover">↓</div><div><b>{x.title}</b><span>{x.artist} · {x.state}</span><i><em style={{width: `${x.progress}%`}} /></i></div><small>{x.progress}%</small></div>)}</div> : <div className="empty"><b>Nothing downloaded yet.</b><br/>Search for something you love and download it with one click.</div>}</>
    if (page === 'Liked Songs') return <><Title label="Collection" title="Liked Songs"/>{tracks([...starter, ...queue].filter((x, i, all) => likes.includes(x.id) && all.findIndex(y => y.id === x.id) === i))}</>
    if (page === 'Recently Played') return <><Title label="History" title="Recently Played"/>{tracks(history)}</>
    if (page === 'Your Library') return <><Title label="Local music" title="Your Library" copy="Downloaded and imported tracks appear here, playable offline."/>{tracks(downloads.filter(x => x.state === 'completed'))}</>
    if (page === 'Playlists') return <><Title label="Collection" title="Your Playlists"/><div className="create"><input value={newPlaylist} onChange={e => setNewPlaylist(e.target.value)} onKeyDown={e => { if(e.key === 'Enter' && newPlaylist.trim()){ setPlaylists(v => [...v, {name:newPlaylist.trim(),tracks:[]}]); setNewPlaylist('') } }} placeholder="New playlist name"/><button onClick={() => { if(newPlaylist.trim()){setPlaylists(v => [...v,{name:newPlaylist.trim(),tracks:[]}]);setNewPlaylist('');tell('Playlist created')}}}>Create playlist</button></div>{playlists.length ? <div className="cards">{playlists.map(x => <article key={x.name}><div>♫</div><b>{x.name}</b><span>{x.tracks.length} tracks</span></article>)}</div> : <div className="empty">Create your first playlist.</div>}</>
    if (page === 'Settings') return <><Title label="System" title="Settings & diagnostics" copy="nont keeps media, metadata and playback local."/><div className="settings"><p><span>Desktop runtime</span><b>{native ? 'Connected' : 'Web preview — native runtime required'}</b></p><p><span>Downloader</span><b>yt-dlp health check runs in desktop runtime</b></p><p><span>Media processing</span><b>FFmpeg health check runs in desktop runtime</b></p><p><span>Storage</span><b>Choose a music folder in desktop runtime</b></p></div></>
    return <><section className="hero"><small>GOOD TO HAVE YOU HERE</small><h1>Your music.<br/><em>On your terms.</em></h1><p>A local-first music home for your library, queue and downloads.</p><button onClick={() => setPage('Search')}>Start searching →</button></section><div className="section"><h2>Continue listening</h2>{tracks(history.length ? history.slice(0,4) : starter)}</div></>
  }
  const nav: Page[] = ['Home','Search','Your Library','Playlists','Downloads','Liked Songs','Recently Played','Settings']
  return <main className="shell"><aside><strong className="brand">nont<span>.</span></strong><nav>{nav.map(x => <button className={page === x ? 'selected' : ''} onClick={() => setPage(x)} key={x}>{x === 'Home' ? '◈' : x === 'Search' ? '⌕' : x === 'Downloads' ? '↓' : x === 'Settings' ? '⚙' : '◌'} <span>{x}</span></button>)}</nav><footer><b>Local profile</b><span>{downloads.length} download jobs</span><small>Local-first · no account</small></footer></aside><section className="main"><header><form onSubmit={(e: FormEvent) => {e.preventDefault(); if(query.trim())setPage('Search')}}><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="What do you want to play?"/><kbd>⌘ K</kbd></form><small className="runtime"><i/> {native ? 'Desktop connected' : 'Preview mode'}</small></header><article className="content">{body()}</article></section>{current && <div className="player"><div className="now"><div className="cover">♪</div><p><b>{current.title}</b><span>{current.artist}</span></p></div><div className="controls"><button onClick={() => setPlaying(!playing)}>{playing ? 'Ⅱ' : '▶'}</button><i><em/></i><small>0:00 / {current.duration}</small></div><small>Queue <b>{queue.length}</b></small></div>}{toast && <div className="toast">{toast}</div>}</main>
}
function Title({label,title,copy}:{label:string,title:string,copy?:string}){return <section className="title"><small>{label}</small><h1>{title}</h1>{copy && <p>{copy}</p>}</section>}
export default App
